[workspace]
members = ["demo-server", "log-wasm"]
resolver = "2"

[workspace.dependencies]
# config
dotenvy = { version = "0.15.7" }
clap = { version = "4.6.1", features = ["env", "derive"] }

# web
tokio = { version = "1.0", features = ["full"] }
hyper = { version = "1.0", features = ["full"] }
hyper-util = { version = "0.1", features = ["client", "client-legacy", "http1", "http2", "tokio"] }
http-body-util = { version = "0.1" }

[package]
name = "reverse-proxy"
description = "Extensible reverse proxy for exam project"
version = "0.1.0"
edition = "2024"
authors = ["William Jelgren <william@jelgren.dk>"]

[features]
default = ["ffi", "wasm"]

ffi = ["dep:libloading"]
wasm = ["dep:wasmtime"]

[dependencies]
# config
dotenvy.workspace = true
clap.workspace = true
kdl = { version = "6.5.0" }

# web stuff
tokio.workspace = true
hyper.workspace = true
http-body-util.workspace = true
hyper-util = { workspace = true, features = ["client", "client-legacy", "http1", "http2", "tokio"] }
bytes = { version = "1.0" }

# serialization
serde = { version = "1.0", features = ["derive"] }
serde_bytes = { version = "0.11" }
rmp-serde = { version = "1.0" }

# ffi
libloading = { version = "0.9", optional = true }

# wasm
wasmtime = { version = "44.0", optional = true }
